package identity

import (
	"math/big"

	core "github.com/iden3/go-iden3-core"
)

/// Identity Profiles allow users to hide their Genesis Identifier during interactions. Instead, users will be identified
/// by their Identity Profile. An Identity Profile is generated by hashing the id with a profile_nonce. This is a random
/// number that is generated by the identity owner.
func Profile(id core.ID) core.ID {
	// 50 is the random number that the identity owner knows 
	profile, _ := core.ProfileID(id, big.NewInt(50))

	return profile
}
